# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-30 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.account'),
        ),
    ]
