# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-30 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180930_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='namep',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
