# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-30 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20180930_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='namep',
            new_name='person',
        ),
    ]
