# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-01 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_mails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mails',
            new_name='mail',
        ),
    ]
